FROM python:3.10-slim

WORKDIR /opt/project

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    libssl-dev \
    openssl \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-dbt.txt /requirements-dbt.txt
RUN pip install --no-cache-dir -r /requirements-dbt.txt

CMD ["bash"]