-- Database & Schema
CREATE DATABASE IF NOT EXISTS DEV;

CREATE SCHEMA IF NOT EXISTS DEV.RAW;
CREATE SCHEMA IF NOT EXISTS DEV.ANALYTICS;


-- File Format
CREATE OR REPLACE FILE FORMAT DEV.RAW.TMDB_JSON_FF
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE
    IGNORE_UTF8_ERRORS = TRUE;

-- External Stages
CREATE OR REPLACE STAGE DEV.RAW.TMDB_TRENDING_STAGE
    URL = 's3://{{ bucket }}/{{ prefix }}/trending/'
    CREDENTIALS = (
        AWS_KEY_ID = '{{ aws_key_id }}'
        AWS_SECRET_KEY = '{{ aws_secret_key }}'
    )
    FILE_FORMAT = DEV.RAW.TMDB_JSON_FF;

CREATE OR REPLACE STAGE DEV.RAW.TMDB_DETAILS_STAGE
    URL = 's3://{{ bucket }}/{{ prefix }}/details/'
    CREDENTIALS = (
        AWS_KEY_ID = '{{ aws_key_id }}'
        AWS_SECRET_KEY = '{{ aws_secret_key }}'
    )
    FILE_FORMAT = DEV.RAW.TMDB_JSON_FF;

CREATE OR REPLACE STAGE DEV.RAW.TMDB_CREDITS_STAGE
    URL = 's3://{{ bucket }}/{{ prefix }}/credits/'
    CREDENTIALS = (
        AWS_KEY_ID = '{{ aws_key_id }}'
        AWS_SECRET_KEY = '{{ aws_secret_key }}'
    )
    FILE_FORMAT = DEV.RAW.TMDB_JSON_FF;

-- RAW Tables
CREATE OR REPLACE TABLE DEV.RAW.TMDB_TRENDING_RAW (
    MEDIA_TYPE STRING,
    TIME_WINDOW STRING,
    PAYLOAD VARIANT,
    SNAPSHOT_DATE DATE,
    LOAD_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV.RAW.TMDB_DETAILS_RAW (
    TMDB_ID NUMBER,
    MEDIA_TYPE STRING,
    PAYLOAD VARIANT,
    LOAD_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV.RAW.TMDB_CREDITS_RAW (
    TMDB_ID NUMBER,
    MEDIA_TYPE STRING,
    PAYLOAD VARIANT,
    LOAD_TS TIMESTAMP_NTZ
);


-- Constraints (Doc purpose)
ALTER TABLE DEV.RAW.TMDB_DETAILS_RAW
    ADD CONSTRAINT PK_DETAILS PRIMARY KEY (TMDB_ID, MEDIA_TYPE);

ALTER TABLE DEV.RAW.TMDB_CREDITS_RAW
    ADD CONSTRAINT PK_CREDITS PRIMARY KEY (TMDB_ID, MEDIA_TYPE);