-- Role
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_ROLE;

-- Database & Schemas
GRANT USAGE ON DATABASE DEV TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DEV.RAW TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

-- RAW: dbt reads only
GRANT SELECT ON ALL TABLES IN SCHEMA DEV.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV.RAW TO ROLE DBT_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA DEV.RAW TO ROLE DBT_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA DEV.RAW TO ROLE DBT_ROLE;

GRANT USAGE ON FILE FORMAT DEV.RAW.TMDB_JSON_FF TO ROLE DBT_ROLE;

-- ANALYTICS: dbt writes here
GRANT CREATE TABLE ON SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA DEV.ANALYTICS TO ROLE DBT_ROLE;

-- Attach role to user
GRANT ROLE DBT_ROLE TO USER DBT_SVC;