-- This script creates DW schema and related tables

CREATE SCHEMA IF NOT EXISTS DEV.DW;

-- Dimension: content metadata
CREATE TABLE IF NOT EXISTS DEV.DW.DIM_CONTENT (
    CONTENT_SK          NUMBER      AUTOINCREMENT,
    TMDB_ID             NUMBER      NOT NULL,
    MEDIA_TYPE          STRING      NOT NULL,
    TITLE               STRING,
    ORIGINAL_TITLE      STRING,
    ORIGINAL_LANGUAGE   STRING,
    RELEASE_DATE        DATE,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_DIM_CONTENT PRIMARY KEY (CONTENT_SK),
    CONSTRAINT UQ_DIM_CONTENT UNIQUE (TMDB_ID, MEDIA_TYPE)
);

-- Fact table: daily/weekly trending metrics
CREATE TABLE IF NOT EXISTS DEV.DW.FACT_TRENDING (
    TRENDING_DATE    DATE          NOT NULL,
    TIME_WINDOW      STRING        NOT NULL,       -- 'day' or 'week'
    CONTENT_SK       NUMBER        NOT NULL,
    POPULARITY       FLOAT,
    VOTE_COUNT       NUMBER,
    VOTE_AVERAGE     FLOAT,
    LOAD_TS          TIMESTAMP_LTZ NOT NULL,
    CREATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_FACT_TRENDING PRIMARY KEY (TRENDING_DATE, TIME_WINDOW, CONTENT_SK),
    CONSTRAINT FK_FACT_TRENDING_CONTENT
        FOREIGN KEY (CONTENT_SK)
        REFERENCES DEV.DW.DIM_CONTENT (CONTENT_SK)
);