
-- DIM_CONTENT: upsert (cumulative dimension)
MERGE INTO DEV.DW.DIM_CONTENT AS d
USING (
    SELECT DISTINCT
        TMDB_ID,
        MEDIA_TYPE,
        TITLE,
        ORIGINAL_TITLE,
        ORIGINAL_LANGUAGE,
        RELEASE_DATE
    FROM DEV.STG.TMDB_TRENDING_STG
    WHERE TRENDING_DATE = TO_DATE('{{ ds }}')
) AS s
ON d.TMDB_ID = s.TMDB_ID
   AND d.MEDIA_TYPE = s.MEDIA_TYPE
WHEN MATCHED THEN UPDATE SET
    d.TITLE             = s.TITLE,
    d.ORIGINAL_TITLE    = s.ORIGINAL_TITLE,
    d.ORIGINAL_LANGUAGE = s.ORIGINAL_LANGUAGE,
    d.RELEASE_DATE      = s.RELEASE_DATE,
    d.UPDATED_AT        = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    TMDB_ID,
    MEDIA_TYPE,
    TITLE,
    ORIGINAL_TITLE,
    ORIGINAL_LANGUAGE,
    RELEASE_DATE
) VALUES (
    s.TMDB_ID,
    s.MEDIA_TYPE,
    s.TITLE,
    s.ORIGINAL_TITLE,
    s.ORIGINAL_LANGUAGE,
    s.RELEASE_DATE
);


-- FACT_TRENDING: snapshot replace for {{ ds }}
DELETE FROM DEV.DW.FACT_TRENDING
WHERE TRENDING_DATE = TO_DATE('{{ ds }}');


INSERT INTO DEV.DW.FACT_TRENDING (
    TRENDING_DATE,
    TIME_WINDOW,
    CONTENT_SK,
    POPULARITY,
    VOTE_COUNT,
    VOTE_AVERAGE,
    LOAD_TS
)
SELECT
    s.TRENDING_DATE,
    s.TIME_WINDOW,
    d.CONTENT_SK,
    s.POPULARITY,
    s.VOTE_COUNT,
    s.VOTE_AVERAGE,
    s.LOAD_TS
FROM DEV.STG.TMDB_TRENDING_STG s
JOIN DEV.DW.DIM_CONTENT d
  ON s.TMDB_ID = d.TMDB_ID
 AND s.MEDIA_TYPE = d.MEDIA_TYPE
WHERE s.TRENDING_DATE = TO_DATE('{{ ds }}');