[pytest]
minversion = 7.0

testpaths = 
    tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

norecursedirs = 
    dags
    plugins
    .git
    venv
    __pycache__

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
