-- This script creats STG schema and tables
CREATE SCHEMA IF NOT EXISTS DEV.STG;

CREATE TRANSIENT TABLE IF NOT EXISTS DEV.STG.TMDB_TRENDING_STG (
    TRENDING_DATE      DATE,
    TIME_WINDOW        STRING,
    MEDIA_TYPE         STRING,

    TMDB_ID            NUMBER,
    TITLE              STRING,

    ORIGINAL_TITLE     STRING,
    ORIGINAL_LANGUAGE  STRING,
    RELEASE_DATE       DATE,

    POPULARITY         FLOAT,
    VOTE_COUNT         NUMBER,
    VOTE_AVERAGE       FLOAT,

    LOAD_TS            TIMESTAMP_LTZ,

    IS_ADULT           BOOLEAN,
    ORIGINAL_NAME      STRING,
    POSTER_PATH        STRING,
    BACKDROP_PATH      STRING
);